#define WRAPAROUND		0x2000
//variables
u8 stage = 0;
u8 loopbreak = 0;
u8 hill_enablesonic = 0;
u8 hill_sonix = 0;
u8 run_statictrigger = 0;
u8 run_sonix = 0;
u8 g_newframe = 0;
int bgx = 0;
u8 playerframe = 0;
u8 filepaltoggle = 0;
u8 run_sonicside = 0;
u8 hill_statictrigger = 0;
#define storagebank0 0x02000000; //For Quick access to LZ77 pre-decompressed data, so it will not take so much time to be visible.
#define storagebank1 0x02012C00;
#define storagebank2 0x02025800;
#define storagebank3 0x02038400;
u8 moving = 0;
#define CHAR_BASE(n)		n<<2
#define BG_COLOR_256		0x80
int frames = 0;
u8 animframe;
u8 pressinglr = 0;
u8 hide_2spooky4metrig = 0;
u8 hide_spookpos = 0;
int rng = 0;
u8 hide_enablesonic = 0;
u8 hide_sonix = 0;
extern const unsigned short bg_disclaimerBitmap[19200];
extern const unsigned short bg_disclaimerPalette[256];
extern const unsigned short bg_static_1Bitmap[19200];
extern const unsigned short bg_static_1Palette[256];
extern const unsigned short bg_static_2Bitmap[19200];
extern const unsigned short bg_static_2Palette[256];
extern const unsigned short bg_static_3Bitmap[19200];
extern const unsigned short bg_static_3Palette[256];
extern const unsigned short title_demonicBitmap[38400];
extern const unsigned short title_frame1Palette[256];
extern const unsigned short title_frame1Bitmap[19200];
extern const unsigned short title_frame2Palette[256];
extern const unsigned short title_frame2Bitmap[19200];
extern const unsigned short bg_datasel_rPalette[256];
extern const unsigned short bg_datasel_rBitmap[19200];
extern const unsigned short bg_datasel_kPalette[256];
extern const unsigned short bg_datasel_kBitmap[19200];
extern const unsigned short bg_datasel_tPalette[256];
extern const unsigned short bg_datasel_tBitmap[19200];
extern const unsigned short t_crai_1Tiles[1024];
extern const unsigned short t_crai_1Pal[16];
extern const unsigned short t_crai_2Tiles[1024];
extern const unsigned short t_crai_2Pal[16];
extern const unsigned short t_dedTiles[1024];
extern const unsigned short t_dedPal[16];
extern const unsigned short t_heyTiles[1024];
extern const unsigned short t_heyPal[16];
extern const unsigned short t_idle_1Tiles[1024];
extern const unsigned short t_idle_1Pal[16];
extern const unsigned short t_idle_2Tiles[1024];
extern const unsigned short t_idle_2Pal[16];
extern const unsigned short t_idle_3Tiles[1024];
extern const unsigned short t_idle_3Pal[16];
extern const unsigned short t_idle_4Tiles[1024];
extern const unsigned short t_idle_4Pal[16];
extern const unsigned short t_pointTiles[1024];
extern const unsigned short t_pointPal[16];
extern const unsigned short t_run_1Tiles[1024];
extern const unsigned short t_run_1Pal[16];
extern const unsigned short t_run_2Tiles[1024];
extern const unsigned short t_run_2Pal[16];
extern const unsigned short t_run_3Tiles[1024];
extern const unsigned short t_run_3Pal[16];
extern const unsigned short t_run_4Tiles[1024];
extern const unsigned short t_run_4Pal[16];
extern const unsigned short t_run_5Tiles[1024];
extern const unsigned short t_run_5Pal[16];
extern const unsigned short t_run_6Tiles[1024];
extern const unsigned short t_run_6Pal[16];
extern const unsigned short t_run_7Tiles[1024];
extern const unsigned short t_run_7Pal[16];
extern const unsigned short t_run_8Tiles[1024];
extern const unsigned short t_run_8Pal[16];
extern const unsigned short t_spooked_1Tiles[1024];
extern const unsigned short t_spooked_1Pal[16];
extern const unsigned short t_spooked_2Tiles[1024];
extern const unsigned short t_spooked_2Pal[16];
extern const unsigned short t_surpTiles[1024];
extern const unsigned short t_surpPal[16];
extern const unsigned short s_sleep_1Pal[16];
extern const unsigned short s_sleep_1Tiles[512];
extern const unsigned short s_sleep_2Pal[16];
extern const unsigned short s_sleep_2Tiles[512];
extern const unsigned short s_spookPal[16];
extern const unsigned short s_spookTiles[512];
extern const unsigned short s_spookPal[16];
extern const unsigned short s_spookTiles[512];
extern const unsigned short bg_hillTiles[32800];
extern const unsigned short bg_hillMap[1024];
extern const unsigned short bg_hillPal[256];
extern const unsigned short bg_hill_bluudyTiles[32800];
extern const unsigned short bg_hill_bluudyMap[1024];
extern const unsigned short bg_hill_bluudyPal[256];
extern const unsigned short bg_hideTiles[32800];
extern const unsigned short bg_hideMap[1024];
extern const unsigned short bg_hidePal[256];
extern const unsigned short bg_hill_startPalette[256];
extern const unsigned short bg_hill_startBitmap[19200];
extern const unsigned short bg_hide_startPalette[256];
extern const unsigned short bg_hide_startBitmap[19200];
extern const unsigned short bg_playPalette[256];
extern const unsigned short bg_playBitmap[19200];
extern const unsigned short s_gattagofastTiles[1024];
extern const unsigned short s_gattagofastPal[16];
extern const unsigned short s_crouchTiles[1024];
extern const unsigned short s_crouchPal[16];
extern const unsigned short s_pwnTiles[1024];
extern const unsigned short s_pwnPal[16];
extern const unsigned short bg_slowPalette[256];
extern const unsigned short bg_slowBitmap[19200];
extern const unsigned short k_crai_1Tiles[1024];
extern const unsigned short k_crai_1Pal[16];
extern const unsigned short k_crai_2Tiles[1024];
extern const unsigned short k_crai_2Pal[16];
extern const unsigned short k_dedTiles[1024];
extern const unsigned short k_dedPal[16];
extern const unsigned short k_idleTiles[1024];
extern const unsigned short k_idlePal[16];
extern const unsigned short k_run_1Tiles[1024];
extern const unsigned short k_run_1Pal[16];
extern const unsigned short k_run_2Tiles[1024];
extern const unsigned short k_run_2Pal[16];
extern const unsigned short k_run_3Tiles[1024];
extern const unsigned short k_run_3Pal[16];
extern const unsigned short k_run_4Tiles[1024];
extern const unsigned short k_run_4Pal[16];
extern const unsigned short k_run_5Tiles[1024];
extern const unsigned short k_run_5Pal[16];
extern const unsigned short k_run_6Tiles[1024];
extern const unsigned short k_run_6Pal[16];
extern const unsigned short k_run_7Tiles[1024];
extern const unsigned short k_run_7Pal[16];
extern const unsigned short k_run_8Tiles[1024];
extern const unsigned short k_run_8Pal[16];
extern const unsigned short k_spookTiles[1024];
extern const unsigned short k_spookPal[16];
extern const unsigned short bg_runTiles[32768];
extern const unsigned short bg_runMap[1024];
extern const unsigned short bg_runPal[256];
extern const unsigned short bg_run_startPalette[256];
extern const unsigned short bg_run_startBitmap[19200];
extern const unsigned short bg_run_bluudTiles[32768];
extern const unsigned short bg_run_bluudMap[1024];
extern const unsigned short bg_run_bluudPal[256];